services:

  api2sbs:
    image: ghcr.io/kx1t/docker-api2sbs
    container_name: api2sbs
    hostname: api2sbs
    restart: always
    # env vars:
    # SBS_SERVER: hostname or IP of SBS server to send data to. Optional; default is ultrafeeder
    # SBS_PORT: port of SBS server to send data to. Optional; default is 32006
    # LOCATIONS: list of locations to retrieve data for. Format is <lat>,<lon>,<radius> with a max radius of 250 miles.
    #            Multiple locations can be specified by separating them with a semicolon. Mandatory - container won't work without it.
    #            Example: LOCATIONS=6,-75,250;15.25,-77.25,250
    # TZ: timezone to use for logging. Optional; default is UTC
    # STATS_INTERVAL: interval in seconds to log stats. Optional; default is 300. Set to 0/off/disabled to disable stats logging.
    #
    # API_URL: URL of the API to retrieve data from. These will work if they more or less conform to the "ADSBExchange V2 API" and provide
    #          data in the airplanes.json format.
    # JSON_AIRCRAFT_KEY: key in the JSON data to look for aircraft data. Optional; default is "ac"
    # API_AUTH: Authorization key to send to the API using the "api-auth" header. Optional; default is none. This is required
    #           for some APIs, such as ADSBExchange (where you should send your feeder's UUID as the key).
    # Examples:
    # - API_URL=https://api.airplanes.live/v2/point/{LAT}/{LON}/{DIST}
    # - JSON_AIRCRAFT_KEY=ac
    #   ^^ These are the default values for API_URL and JSON_AIRCRAFT_KEY if omitted
    #
    # - API_URL=https://opendata.adsb.fi/api/v2/lat/{LAT}/lon/{LON}/dist/{DIST}
    # - JSON_AIRCRAFT_KEY=aircraft
    #
    # - API_URL=https://adsbexchange.com/api/aircraft/lat/{LAT}/lon/{LON}/dist/{DIST}/
    # - JSON_AIRCRAFT_KEY=ac
    # - API_AUTH=YOUR_UUID_HERE
    #
    # Note - you can also use the aircraft.json endpoint of a tar1090 instance as the API_URL. In this case,
    #        you don't need to set the LOCATION, JSON_AIRCRAFT_KEY, or API_AUTH as those aren't supported.
    #        WARNING - make sure you do not create a data loop by getting your data from the same instance you feed it to.
    #        Example:
    # - API_URL=https://someones.tar1090.instance/data/aircraft.json
    #
    environment:
      - TZ=America/New_York
      - SBS_SERVER=ultrafeeder
      - SBS_PORT=32006
      - LOCATIONS=
          6,-75,250;
          15.25,-77.25,250;
      # - STATS_INTERVAL=60    
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=32M
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=32M
